server:
  port: 8080

#spring:
#  jackson:
#    serialization:
#      write-dates-as-timestamps: false
#  datasource:
#    url: jdbc:mysql://192.168.1.35/sb-airlines
#    username: root
#    password: 1234
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MariaDB53Dialect
#  application:
#    name: FARES-SERVER

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:mysql://127.0.0.1:33060/sb-airlines-fare
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: FARES-SERVER
    
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE